analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.75
cta: {}
layout_spectrum: 0.37465
name: nicolas joseph
opengraph: {}
purpose: []
typography_spectrum: 0.810855
